### ISSUE TITLE
gernest/cute/style/stypes.go:86:15: vecty.Markup is not a type

### ISSUE THREAD

**Issue by ghost** [gernest/cute#1]
they changed the way you do markup in vecty recently....

**Comment by bzub** [comment]
I've implemented the vecty changes in my fork: https://gitlab.com/agamigo/forks/cute/merge_requests/1

Needs to be tested though, then I will submit a PR here.

**Comment by ghost** [comment]
thanks for letting me know :)

**Comment by ghost** [comment]
reopening  to so commenter @bzub  can push PR back when ready.
